version: '3'
services:
  db:
    image: postgres:latest
    container_name: apartments_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ApartmentsDB
    ports:
      - "5432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d

  backend:
    build: ./backend
    container_name: apartments_backend
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: admin
      DB_PASS: admin
      DB_NAME: ApartmentsDB
    ports:
      - "5000:5000"
    depends_on:
      - db
      
  frontend:
    build: ./frontend
    container_name: apartments_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
  

